Accept file names includes one or more space characters. Add verbosity level 2. Add debug option. Clarify processing style on a dryrun. Clarify usage of shell quotes (single and double quotes, and escapes)

diff --git a/dump-android-partitions b/dump-android-partitions
--- a/dump-android-partitions
+++ b/dump-android-partitions
@@ -16,6 +16,8 @@ $progname -l {-a|PARTITION ...}
 $progname -h
   -a
     dump all partitions except those designated with -x option
+  -D
+    echoing debugging messages
   -l
     list partition names on a device and exit
   -p GLOB
@@ -38,26 +40,31 @@ $progname -h
   -h
     print this message and exit
   -v
-    verbosely echoing information messages
+    verbosely echoing information messages (verbosity level 1)
+  -v -v
+    verbosely echoing information messages (verbosity level 2)
   -n
-    dry-run
+    dry-run (implies single -v)
   PARTITION
-    a partition name to be dumped
+    a partition name to be dumped. shell globbing available
 "
 
 tmpfile=
 cleanup=
-verbose=false
+verbose1=false
+verbose2=false
 dryrun=false
 listp=false
 testmodep=false
 allp=false
+debug=false
 excludefile="$DEFAULT_EXCLUDE_FILE"
 workdir="$DEFAULT_REMOTE_WORKDIR_FOR_TESTMODE"
 globs=()
 while true; do
   case "$1" in
   -a) allp=true; shift;;
+  -D) debug=true; shift;;
   -l) listp=true; shift;;
   -p) globs+=("$2"); shift 2;;
   -s) serial="$2"; shift 2;;
@@ -65,8 +72,8 @@ while true; do
   -w) workdir="$2"; shift 2;;
   -x) excludefile="$2"; shift 2;;
   -h) echo "$usage"; exit 0;;
-  -v) verbose=true; shift;;
-  -n) dryrun=true; shift;;
+  -n) dryrun=true; $verbose1 && verbose2=true; verbose1=true; shift;;
+  -v) $verbose1 && verbose2=true; verbose1=true; shift;;
   -*) shift;;
   *) break;;
   esac
@@ -81,11 +88,14 @@ list_adb_devices() {
 }
 
 number_of_adb_devices() {
-  list_adb_devices | if [ -n "$serial" ]; then grep "^$serial	"; else cat -; fi | wc -l
+  list_adb_devices | if [ -n "$serial" ]; then grep "^$serial"; else cat -; fi | wc -l
 }
 
 _adb() {
+  $debug && echo debug: adb ${serial:+-s $serial} "$@">&2
+  $debug && set -x
   adb ${serial:+-s $serial} "$@"
+  $debug && set +x
 }
 
 adb_shell() {
@@ -97,12 +107,12 @@ adb_echo_result() {
 }
 
 adb_return_result() {
-  rc="`adb_echo_result \"\$@\"`"
+  rc=`adb_echo_result "$@"`
   return $rc
 }
 
 remote_cmd_not_exist() {
-  rc="`adb_echo_result \"\$@\"`"
+  rc=`adb_echo_result "$@"`
   test "$rc" = "127"
 }
 
@@ -121,14 +131,19 @@ remote_su_not_exist() {
   remote_cmd_not_exist su -c echo
 }
 
+_run() {
+  $verbose1 && echo "$@">&2
+  $dryrun || eval "$@"
+}
+
 get_partitions_list_dir() {
   declare -n partListGlobs=$1
   partListDir=
   for glob in ${partListGlobs[@]}; do
-    $verbose && echo "glob for partitions list directory: $glob">&2
+    $verbose2 && echo "glob for partitions list directory: $glob">&2
     partListDirs=`adb_shell $sucmd echo "$glob"`
     partListDirs_len=`echo "$partListDirs" | wc -w`
-    $verbose && echo "partitions list directory: $partListDirs">&2
+    $verbose2 && echo "partitions list directory: $partListDirs">&2
     if [ $partListDirs_len -eq 1 ] && adb_return_result $sucmd test -d "$partListDirs"; then
       partListDir="$partListDirs"
       break
@@ -169,7 +184,7 @@ if remote_cmd_not_exist id; then
   exit 2
 fi
 if remote_adb_is_rooted; then
-  sucmd=''
+  sucmd='sh -c'
 elif remote_su_not_exist; then
   echo "$progname: Unable to dump: There are neither rooted adbd nor su command on the device. Solution: TWRP recovery or root the device.">&2
   exit 2
@@ -199,7 +214,7 @@ fi
 partsLen=`echo "$parts" | wc -w`
 
 
-$verbose && echo "partitions: $parts"
+$verbose2 && echo "partitions: $parts">&2
 ipart=0
 for part in $parts; do
   cleanup=
@@ -218,29 +233,25 @@ for part in $parts; do
     done
     echo
     $testmodep && {
-      #$verbose && echo ""
-      cleanup="rm -rf '$tmpfile'; adb_shell $sucmd rm -f '$workdir/$part.img'"
+      cleanup="rm -rf '$tmpfile'; adb_shell '$sucmd rm -f \"$workdir/$part.img\"'"
       $dryrun || {
         trap "$cleanup" EXIT
         tmpfile=`mktemp` || {
           echo "$progname: TEST mode: $tmpfile: cannot create temporary directory.">&2; break; }
       }
-      $dryrun || adb_return_result $sucmd dd if="$partListDir/$part" of="$workdir/$part.img" bs=1048576 || {
+      _run "adb_return_result '$sucmd \"dd if=\\\"$partListDir/$part\\\" of=\\\"$workdir/$part.img\\\" bs=1048576\"'" || {
         echo "$progname: TEST mode: remote dd for partition:$part failed. Skip it.">&2; break; }
-      $dryrun || adb_return_result $sucmd chmod 644 "$workdir/$part.img" || {
+      _run "adb_return_result '$sucmd \"chmod 644 \\\"$workdir/$part.img\\\"\"'" || {
         echo "$progname: TEST mode: chmod for file:$part.img failed. Skip partition:$part.">&2; break; }
-      #$verbose && echo ""
-      $dryrun || adb pull "$workdir/$part.img" `cygpath -w "$tmpfile"` >/dev/null || {
+      _run "adb pull '$workdir/$part.img' '`cygpath -w \"$tmpfile\"`' >/dev/null" || {
         echo "$progname: TEST mode: adb pull for partition:$part failed. Skip it.">&2; break; }
     }
-    $verbose && echo "adb_shell $sucmd \"cat $partListDir/$part\" >\"$part.img\""
-    $dryrun || adb_shell $sucmd "cat $partListDir/$part" >"$part.img"
+    _run "adb_shell '$sucmd cat \"$partListDir/$part\"' >\"$part.img\""
     $testmodep && {
-      #$verbose && echo ""
-      $dryrun || if cmp "$tmpfile" "$part.img"; then
-          echo "TEST mode: Ok (A dumped image completely same with that by dd)."
+      if _run "cmp '$tmpfile' '$part.img'"; then
+          $dryrun || echo "TEST mode: Ok (A dumped image completely same with that by dd)."
         else
-          echo "TEST mode: Fail (A dumped image differs from that by dd). possible bug in $0."
+          $dryrun || echo "TEST mode: Fail (A dumped image differs from that by dd). possible bug in $0."
         fi
     }
     break;
